"""
Django settings for DBL_Free project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import DBL_Free.config as cfg

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = cfg.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = cfg.DEBUG

ALLOWED_HOSTS = cfg.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dblfree.apps.DblfreeConfig',
]

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DBL_Free.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DBL_Free.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': cfg.DATABASE
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_ROOT = 'media/'
MEDIA_URL = 'media/'

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

HCAPTCHA_SITEKEY = cfg.HCAPTCHA_SITEKEY
HCAPTCHA_SECRET = cfg.HCAPTCHA_SECRET

HYVOR_TALK_WEBSITE = cfg.HYVOR_TALK_WEBSITE

EMAIL_BACKEND = cfg.EMAIL_BACKEND
EMAIL_HOST = cfg.EMAIL_HOST
EMAIL_HOST_USER = cfg.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = cfg.EMAIL_HOST_PASSWORD
EMAIL_PORT = cfg.EMAIL_PORT
EMAIL_USE_TLS = cfg.EMAIL_USE_TLS
DEFAULT_FROM_EMAIL = cfg.DEFAULT_FROM_EMAIL
CONTACT_EMAIL = cfg.CONTACT_EMAIL

CSP_DEFAULT_SRC = ("'none'",)
CSP_SCRIPT_SRC = ("'self'", 'https://talk.hyvor.com', 'https://hcaptcha.com', 'https://*.hcaptcha.com')
CSP_IMG_SRC = ("'self'", 'data:', 'https://talk.hyvor.com')
CSP_FRAME_SRC = ('https://talk.hyvor.com', 'https://hcaptcha.com', 'https://*.hcaptcha.com')
CSP_FONT_SRC = ('https://fonts.gstatic.com',)
CSP_CONNECT_SRC = ("'self'", 'https://hcaptcha.com')
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", 'https://*.hcaptcha.com', 'https://fonts.googleapis.com')
CSP_NAVIGATE_TO = ("'self'", 'https://www.hcaptcha.com', 'https://hyvor.com')
CSP_FORM_ACTION = ("'self'",)
CSP_INCLUDE_NONCE_IN = ('script-src',)
